firstLevelName = arg[1]
root = arg[2]
levelsDirectory = "resources/levels/"

if not firstLevelName or not root then
  script = "genlvl.lua"
  print("Usage: " .. script .. [[ <firstLevelName> <pathToGameRoot>

  <pathToGameRoot>/]] .. levelsDirectory
                      .. [[<firstLevelName>.lua must exist.

Examples:
  ]] .. script .. [[ park ..
  ]] .. script .. [[ 'some cool level name' ~/games/mygame]])

  return
end

root = string.gsub(root .. "/", "//", "/")
levelsPath = root .. levelsDirectory
outputPath = root .. "levels.lua"


-- Get all files in levelsPath that end with .lua
stream = io.popen("ls " .. levelsPath .. "*.lua")
files = {}
for path in stream:lines() do
  local name = string.gsub(path, levelsPath .. "(.*).lua", "%1")
  local filePath = levelsPath .. name .. ".lua"

  print('Found "' .. filePath .. '"')
  gotAMatch = name == firstLevelName
  files[#files + 1] = {name=name, path=filePath}
end
stream:close()

if not gotAMatch then
  print('"' .. firstLevelName .. '" not found in ' .. levelsPath)
  return
end


-- Generate module content from files
content = [=[--[[
     This file was automatically generated by genlvl.
     Edit *.lua files in "]=] .. levelsDirectory .. [=[".  
     Don't edit this one: any change you make here will be overwritten.
  ]]
module("levels", package.seeall)


level = {
]=]
for i, file in ipairs(files) do
  io.input(file.path)
  newContent = '  ["' .. file.name .. '"] = ' .. io.read("*all")
  newContent = string.gsub(newContent, "\n", "\n  ")
  newContent = string.gsub(newContent, "}[%s^,]*$", "},\n\n")
  content = content .. newContent
end
content = content .. '}\n\nfirst = "' .. firstLevelName .. '"'
io.output(outputPath)
io.write(content)
print(outputPath)
print(content)
